services:
  e2e:
    image: cypress/included:13.9.0
    build: /cypress
    container_name: cypress
    environment:
      - ENV=development
      - CYPRESS_baseUrl=https://dev.geyser.fund
    working_dir: /cypress
    volumes:
      - ./:/cypress
    network_mode: host

