name: Test
on:
  pull_request:
    branches:
      - 'staging'
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    name: E2E on Chrome
    env:
      CYPRESS_APP_URL: ${{ secrets.APP_URL }}
      CYPRESS_CONTRIBUTOR_LND_ENDPOINT: ${{ secrets.CONTRIBUTOR_LND_ENDPOINT }}
      CYPRESS_CONTRIBUTOR_LND_ADMIN_MACAROON_HEX: ${{ secrets.CONTRIBUTOR_LND_ADMIN_MACAROON_HEX }}
      CYPRESS_MINE_BLOCK_ADDRESS: ${{ secrets.MINE_BLOCK_ADDRESS }}
      CYPRESS_BITCOIND_ENDPOINT: ${{ secrets.BITCOIND_ENDPOINT }}
      CYPRESS_BITCOIND_AUTH: ${{ secrets.BITCOIND_AUTH }}
    container:
      image: cypress/browsers:node-20.13.0-chrome-124.0.6367.155-1-ff-125.0.3-edge-124.0.2478.80-1
      options: --user 1001
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - uses: cypress-io/github-action@v6
