name: Test
on:
  pull_request:
    branches:
      - 'staging'
jobs:
  chrome:
    runs-on: ubuntu-22.04
    name: E2E on Chrome
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          browser: chrome
          env:
            CYPRESS_APP_URL: ${{ secrets.APP_URL }}
            CYPRESS_CONTRIBUTOR_LND_ENDPOINT: ${{ secrets.CONTRIBUTOR_LND_ENDPOINT }}
            CYPRESS_CONTRIBUTOR_LND_ADMIN_MACAROON_HEX: ${{ secrets.CONTRIBUTOR_LND_ADMIN_MACAROON_HEX }}
            CYPRESS_MINE_BLOCK_ADDRESS: ${{ secrets.MINE_BLOCK_ADDRESS }}
            CYPRESS_BITCOIND_ENDPOINT: ${{ secrets.BITCOIND_ENDPOINT }}
            CYPRESS_BITCOIND_AUTH: ${{ secrets.BITCOIND_AUTH }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
